version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  frontend:
    image: node:20
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: ["npm", "start", "start:frontend"]
    environment:
      - CHOKIDAR_USEPOLLING=true